// Generated by scripts/embed-prompts.mjs — do not edit by hand.
import { EXTRACT_V1 } from "./extract.v1.ts";
import { EXTRACT_V2 } from "./extract.v2.ts";
import { RECONCILE_V1 } from "./reconcile.v1.ts";
import { RECONCILE_V2 } from "./reconcile.v2.ts";

export { EXTRACT_V1, EXTRACT_V2, RECONCILE_V1, RECONCILE_V2 };

/** Every embedded prompt by its ref (the file name without .md). */
export const PROMPT_TEXT: Record<string, string> = {
  "extract.v1": EXTRACT_V1,
  "extract.v2": EXTRACT_V2,
  "reconcile.v1": RECONCILE_V1,
  "reconcile.v2": RECONCILE_V2,
};
