// Embeds every prompt under ../prompts as a TypeScript module, so the package
// carries its prompt text as data and never reads the filesystem — a phone, a
// Cloud Run container and a test all get the same bytes. The markdown file
// stays the thing a person edits; `npm run prompts` regenerates, and
// test/prompts.test.ts fails when the two drift.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const promptsDir = resolve(here, "..", "prompts");
const outDir = resolve(here, "..", "src", "prompts");
mkdirSync(outDir, { recursive: true });

const files = readdirSync(promptsDir)
  .filter((name) => name.endsWith(".md"))
  .sort();
const names = [];
for (const file of files) {
  const ref = file.replace(/\.md$/, "");
  const text = readFileSync(join(promptsDir, file), "utf8");
  const constName = ref.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
  names.push({ ref, constName, file });
  writeFileSync(
    join(outDir, `${ref}.ts`),
    [
      `// Generated by scripts/embed-prompts.mjs from prompts/${file} — do not edit by hand.`,
      `export const ${constName} = ${JSON.stringify(text)};`,
      "",
    ].join("\n"),
  );
}
writeFileSync(
  join(outDir, "index.ts"),
  [
    "// Generated by scripts/embed-prompts.mjs — do not edit by hand.",
    ...names.map(({ ref, constName }) => `import { ${constName} } from "./${ref}.ts";`),
    "",
    `export { ${names.map(({ constName }) => constName).join(", ")} };`,
    "",
    "/** Every embedded prompt by its ref (the file name without .md). */",
    "export const PROMPT_TEXT: Record<string, string> = {",
    ...names.map(({ ref, constName }) => `  ${JSON.stringify(ref)}: ${constName},`),
    "};",
    "",
  ].join("\n"),
);
console.log(`embedded ${names.length} prompt(s) into src/prompts`);
